# AUTOGENERATED BY NBDEV! DO NOT EDIT!

__all__ = ["index", "modules", "custom_doc_links", "git_url"]

index = {"Timeapp": "00_core.ipynb"}

modules = ["core.py"]

doc_url = "https://Mikhail Shevchenko.github.io/timeapp/"

git_url = "https://github.com/Mikhail Shevchenko/timeapp/tree/master/"

def custom_doc_links(name): return None
